FROM node:24.14.1-alpine as base

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev \
    pixman-dev \
    pangomm-dev \
    libjpeg-turbo-dev \
    freetype-dev

COPY . .

ARG FRONTEND_URL
ARG GEMINI_API_KEY
ARG WEATHER_API_KEY
ARG WHATSAPP_API_KEY
ARG WHATSAPP_VERIFY_TOKEN
ARG PHONE_NUMBER_ID
ARG VERTEX_PROJECT_ID
ARG VERTEX_LOCATION
ARG VERTEX_COLLECTION
ARG VERTEX_ENGINE_ID
ARG VERTEX_SERVING_CONFIG
ARG VERTEX_PROMPT_SEC
ARG VERTEX_MODEL_VERSION


ENV PORT 8080
ENV FRONTEND_URL=$FRONTEND_URL
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV WEATHER_API_KEY=$WEATHER_API_KEY
ENV WHATSAPP_API_KEY=$WHATSAPP_API_KEY
ENV WHATSAPP_VERIFY_TOKEN=$WHATSAPP_VERIFY_TOKEN
ENV PHONE_NUMBER_ID=$PHONE_NUMBER_ID
ENV VERTEX_PROJECT_ID=$VERTEX_PROJECT_ID
ENV VERTEX_LOCATION=$VERTEX_LOCATION
ENV VERTEX_COLLECTION=$VERTEX_COLLECTION
ENV VERTEX_ENGINE_ID=$VERTEX_ENGINE_ID
ENV VERTEX_SERVING_CONFIG=$VERTEX_SERVING_CONFIG
ENV VERTEX_PROMPT_SEC=$VERTEX_PROMPT_SEC
ENV VERTEX_MODEL_VERSION=$VERTEX_MODEL_VERSION

RUN npm install

RUN npm run build

EXPOSE 8080
CMD ["node", "dist/server.js"]

