export enum ENUM_PADDY_DISEASE {
  "BACTERIAL LEAF BLIGHT",
  "BACTERIAL LEAF STREAK",
  "BACTERIAL PANICLE BLIGHT",
  "BACTERIAL SHEATH BROWN ROT",
  "BAKANAE",
  "BLAST",
  "BROWN SPOT",
  "FALSE SMUT",
  "GRASSY STUNT VIRUS",
  "NARROW BROWN SPOT",
  "RAGGED STUNT VIRUS",
  "SHEATH BLIGHT",
  "SHEATH ROT",
  "STEM ROT",
  "TUNGRO",
  "HEALTHY"
}